# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82b86ce7aa3820e77ea1c2e08f797feeb0747d3e3fa78e260f456422a51024c9105c421541b6f732436d1b4d896dbb8a7f3212670ea6d1324debc337f1987257

test:
  secret_key_base: 8918864ad788ba21f328ce99411ac9c3d9f04307f8c38a2f869b32df57995bf57935a9af6ec0ad0f2a79e0fa29e906bd9b8a740c22d97e9327b14125e45dfafe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
